
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/focal-elf-464303-h6/gemini-develop', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/focal-elf-464303-h6/gemini-develop']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gemini-develop'
      - '--image=gcr.io/focal-elf-464303-h6/gemini-develop'
      - '--region=us-central1' # Change to your preferred region
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/credentials.json' # Replace with your secret manager setup

images:
  - 'gcr.io/focal-elf-464303-h6/gemini-develop'
